url: http://www.seohzz.com

title: Select Web

keywords: 顺德SEO,顺德网站建设,顺德网站推广,顺德网络营销

description: Select Web是分享顺德SEO、网站建设、网站推广和网络营销的博客，为企业提供专业的SEO、网站建设、网站推广和网络营销顾问服务。

relative_permalinks: false

contacts: 霍政和

tel: 13823477441

exclude:
  - README.md
